POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Nüsse",
  "quantity": 200,
  "price": 3.96
}

###
GET http://localhost:8080/products
Accept: application/json

###

###
GET http://localhost:8080/products/61925f47029a922530372310
Accept: application/json

###

